mtg_set_mapping = {
    "LEA": "Alpha",
    "LEB": "Beta",
    "2ED": "Unlimited Edition",
    "ARN": "Arabian Nights",
    "ATQ": "Antiquities",
    "LEG": "Legends",
    "DRK": "The Dark",
    "FEM": "Fallen Empires",
    "ICE": "Ice Age",
    "ALL": "Alliances",
    "MIR": "Mirage",
    "VIS": "Visions",
    "WTH": "Weatherlight",
    "TMP": "Tempest",
    "STH": "Stronghold",
    "EXO": "Exodus",
    "USG": "Urza's Saga",
    "ULG": "Urza's Legacy",
    "UDS": "Urza's Destiny",
    "MMQ": "Mercadian Masques",
    "NEM": "Nemesis",
    "PCY": "Prophecy",
    "INV": "Invasion",
    "PLS": "Planeshift",
    "APC": "Apocalypse",
    "ODY": "Odyssey",
    "TOR": "Torment",
    "JUD": "Judgment",
    "ONS": "Onslaught",
    "LGN": "Legions",
    "SCG": "Scourge",
    "8ED": "Eighth Edition",
    "MRD": "Mirrodin",
    "DST": "Darksteel",
    "5DN": "Fifth Dawn",
    "CHK": "Champions of Kamigawa",
    "BOK": "Betrayers of Kamigawa",
    "SOK": "Saviors of Kamigawa",
    "RAV": "Ravnica: City of Guilds",
    "GPT": "Guildpact",
    "DIS": "Dissension",
    "CSP": "Coldsnap",
    "TSP": "Time Spiral",
    "PLC": "Planar Chaos",
    "FUT": "Future Sight",
    "10E": "Tenth Edition",
    "LRW": "Lorwyn",
    "MOR": "Morningtide",
    "SHM": "Shadowmoor",
    "EVE": "Eventide",
    "ALA": "Shards of Alara",
    "CON": "Conflux",
    "ARB": "Alara Reborn",
    "ZEN": "Zendikar",
    "WWK": "Worldwake",
    "ROE": "Rise of the Eldrazi",
    "M11": "Magic 2011",
    "SOM": "Scars of Mirrodin",
    "MBS": "Mirrodin Besieged",
    "NPH": "New Phyrexia",
    "ISD": "Innistrad",
    "DKA": "Dark Ascension",
    "AVR": "Avacyn Restored",
    "RTR": "Return to Ravnica",
    "GTC": "Gatecrash",
    "DGM": "Dragon's Maze",
    "THS": "Theros",
    "BNG": "Born of the Gods",
    "JOU": "Journey into Nyx",
    "KTK": "Khans of Tarkir",
    "FRF": "Fate Reforged",
    "DTK": "Dragons of Tarkir",
    "BFZ": "Battle for Zendikar",
    "OGW": "Oath of the Gatewatch",
    "SOI": "Shadows over Innistrad",
    "EMN": "Eldritch Moon",
    "KLD": "Kaladesh",
    "AER": "Aether Revolt",
    "AKH": "Amonkhet",
    "HOU": "Hour of Devastation",
    "XLN": "Ixalan",
    "RIX": "Rivals of Ixalan",
    "DOM": "Dominaria",
    "GRN": "Guilds of Ravnica",
    "RNA": "Ravnica Allegiance",
    "WAR": "War of the Spark",
    "M20": "Core Set 2020",
    "ELD": "Throne of Eldraine",
    "THB": "Theros Beyond Death",
    "IKO": "Ikoria: Lair of Behemoths",
    "M21": "Core Set 2021",
    "ZNR": "Zendikar Rising",
    "KHM": "Kaldheim",
    "STX": "Strixhaven: School of Mages",
    "AFR": "Adventures in the Forgotten Realms",
    "MID": "Innistrad: Midnight Hunt",
    "VOW": "Innistrad: Crimson Vow",
    "NEO": "Kamigawa: Neon Dynasty",
    "SNC": "Streets of New Capenna",
    "DMU": "Dominaria United",
    "BRO": "The Brothers' War",
    "ONE": "Phyrexia: All Will Be One",
    "MOM": "March of the Machine",
    "LTR": "The Lord of the Rings: Tales of Middle-earth",
    "LTC": "The Lord of the Rings: Tales of Middle-earth Commander",
    "CMM": "Commander Masters/Commander Masters Decks",
    "WOE": "Wilds of Eldraine",
    "WOT": "Enchanting Tales Bonus Sheet",
    "WOC": "Wilds of Eldraine Commander",
    "WHO": "Doctor Who: Commander Decks",
    "LCI": "The Lost Caverns of Ixalan",
    "LCC": "The Lost Caverns of Ixalan Commander",
    "RVR": "Ravnica Remastered",
    "MKM": "Murders at Karlov Manor",
    "MKC": "Murders at Karlov Manor Commander",
    "CLU": "The Clue Collector's Set",
    "PIP": "Fallout",
    "OTJ": "Outlaws of Thunder Junction",
    "OTP": "Breaking News Bonus Sheet",
    "BIG": "Big Score Bonus Sheet",
    "OTC": "Outlaws of Thunder Junction Commander",
    "MH3": "Modern Horizons 3",
    "M3C": "Modern Horizons 3 Commander",
    "ACR": "Assassin's Creed",
    "BLB": "Bloomburrow",
    "BLC": "Bloomburrow Commander",
    "MB2": "Mystery Booster 2",
    "DSK": "Duskmourn: House of Horrors",
    "DSC": "Duskmourn: House of Horrors Commander",
    "FDN": "Magic: The Gathering Foundations",
    "FDC": "Magic: The Gathering Foundations Commander",
    "J25": "Foundations Jumpstart",
    "INR": "Innistrad Remastered",
    "DFT": "Aether Drift",
    "DRC": "Aether Drift Commander",
    "TDM": "Tarkir: Dragonstorm"
}